### ISSUE TITLE
Add a REQUIRE file

### ISSUE THREAD

**Issue by ararslan** [gerhardtulzer/EllipticFEM.jl#5]
The standard REQUIRE files are required for Julia package registration since they tell METADATA which versions you need. You could translate parts of what you have in the file called Requirements to the necessary REQUIRE format like so:

```
julia 0.4
PyPlot
LightGraphs
```

Non-Julia package dependencies shouldn't be specified in REQUIRE. If any of GMSH, AVConv, or VLC supports interacting via shared libraries then you could set up the repository to use [BinDeps.jl](https://github.com/JuliaLang/BinDeps.jl). Otherwise you should make it clear that those programs need to be not only installed, but available in the user's path.

**Comment by tkelman** [comment]
The package is also missing `src/EllipticFEM.jl` and `test/runtests.jl` files.

**Comment by ararslan** [comment]
Further, in order to register version 0.0.2 in METADATA, you'll need to push the tag to the repository so that it shows up in https://github.com/gerhardtulzer/EllipticFEM.jl/releases.

In your Travis configuration file you're only test on `release`, which is currently Julia 0.5. So it might also be a good idea to update the file to use `0.4`, `0.5`, and `nightly`, as appropriate.

**Comment by gerhardtulzer** [comment]
Thank you for your information! I have added all the necessary files. Can you check if everything is alright now, such that I can close the issue?

**Comment by tkelman** [comment]
`src/EllipticFEM.jl` needs to begin with `module EllipticFEM`

**Comment by tkelman** [comment]
You want Travis CI at https://travis-ci.org/gerhardtulzer/EllipticFEM.jl/builds to be passing, at least on releases of Julia.

Is there anything here that relies on a bug that was not fixed until Julia 0.4.5? If no, then the package should work on all julia 0.4.x versions so the minimum in REQUIRE should be just `0.4`.

**Comment by ararslan** [comment]
Also it looks like your tests aren't using Julia's unit testing framework. It would be good to write tests using `Base.Test`, as is done in most other packages.

**Comment by gerhardtulzer** [comment]
Please check again if everything is alright now. Thank you very much!

**Comment by ararslan** [comment]
The REQUIRE file is looking good. I have a few suggestions for other pieces though:
1. In src/EllipticFEM.jl, the `using` statements should go above the `include`s. Also, if your package is able to be precompiled, I recommend adding `__precompile__()` above the `module` statement.
2. test/runtests.jl should have `using EllipticFEM` at the top.
3. Looks like the still aren't really utilizing the `Base.Test` framework. I recommend taking a look at how other packages do their tests for inspiration.

**Comment by gerhardtulzer** [comment]
I have added some further tests to the `runtests.jl` file. I hope this is OK now. I also added the `using` statements. Do I need to resend a pull request for the `METADATA` repository?
